const ACTION_TYPE = {
  SIGNUP_LOADING: 'SIGNUP_LOADING',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  SIGNUP_ASYNC: 'SIGNUP_ASYNC',

  LOGIN_LOADING,
};

export default ACTION_TYPE;
